 name: Node.js CI
 on:
   push:
     branches: [ main ]
   pull_request:
     branches: [ main ]

 jobs:
   build:

     runs-on: ubuntu-latest

     strategy:
       matrix:
         node-version: [22.x]
         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

     steps:
     - uses: actions/checkout@v4
     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v4
       with:
         node-version: ${{ matrix.node-version }}
         cache: 'npm'
         
   security:
       runs-on: ubuntu-latest
       steps:
         - name: Run OX Security Scan to check for vulnerabilities
           with:
             ox_api_key: ${{ secrets.OX_API_KEY }}
           uses: oxsecurity/ox-security-scan@main
